run_logged $ZANKEN_INSTALL/packaging/base.sh
run_logged $ZANKEN_INSTALL/packaging/fonts.sh
run_logged $ZANKEN_INSTALL/packaging/icons.sh
run_logged $ZANKEN_INSTALL/packaging/webapps.sh
run_logged $ZANKEN_INSTALL/packaging/tuis.sh
run_logged $ZANKEN_INSTALL/packaging/npm.sh
run_logged $ZANKEN_INSTALL/packaging/asus-rog.sh
run_logged $ZANKEN_INSTALL/packaging/framework16.sh
run_logged $ZANKEN_INSTALL/packaging/dell-xps-touchpad-haptics.sh
run_logged $ZANKEN_INSTALL/packaging/surface.sh
