general {
  lock_cmd = zanken-system-lock
  before_sleep_cmd = zanken-system-lock
  after_sleep_cmd = niri msg action power-on-monitors
}

listener {
  timeout = 600
  on-timeout = zanken-system-lock
}
